#!/usr/bin/env bash
set -euo pipefail

DOTFILES_SOURCE=$(pwd)

ln -nsf "$DOTFILES_SOURCE"/zshrc.extras ~/.zshrc.extras
echo "source ~/.zshrc.extras" >> ~/.zshrc

ln -nsf "$DOTFILES_SOURCE"/tmux.conf ~/.tmux.conf
ln -nsf "$DOTFILES_SOURCE"/tmux.conf.ui ~/.tmux.conf.ui
ln -nsf "$DOTFILES_SOURCE"/tmux.conf.ubuntu ~/.tmux.conf.ubuntu
ln -nsf "$DOTFILES_SOURCE"/tmux.conf.osx ~/.tmux.conf.osx

ln -nsf "$DOTFILES_SOURCE"/vimrc ~/.vimrc
mkdir -p ~/.config/nvim
ln -nsf "$DOTFILES_SOURCE"/vimrc ~/.config/nvim/init.vim

ln -nsf "$DOTFILES_SOURCE"/ideavimrc ~/.ideavimrc
ln -nsf "$DOTFILES_SOURCE"/gitignore ~/.gitignore

mkdir -p ~/.config/karabiner/assets/complex_modifications
ln -nsf "$DOTFILES_SOURCE"/karabiner/ctrl-up-down.json ~/.config/karabiner/assets/complex_modifications/ctrl-up-down.json
ln -nsf "$DOTFILES_SOURCE"/karabiner/caps-lock-remapping.json ~/.config/karabiner/assets/complex_modifications/caps-lock-remapping.json

mkdir -p ~/.config/doom
ln -nsf "$DOTFILES_SOURCE"/doom.d ~/.config/doom

if command -v rbenv 2>/dev/null; then
  default_gems_path="$(rbenv root)/plugins/rbenv-default-gems"
  if [ ! -d "${default_gems_path}" ]; then
    git clone https://github.com/rbenv/rbenv-default-gems.git "$(rbenv root)"/plugins/rbenv-default-gems
  fi

  ln -nsf "$DOTFILES_SOURCE"/default-gems "${default_gems_path}"
else
  echo "rbenv not installed"
  echo "Don't forget to symlink default-gems file later!"
fi
