#!/usr/bin/env zsh

function install() {
  case ${os_family} in
    "macos")
      sudo apt install ripgrep
      ;;
    "debian")
      brew install ripgrep
    *)
      echo "OS family: '${os_family}' not supported"
      exit 1
      ;; esac
}

install
