#!/usr/bin/env bash
#
# Common environment user session
#

# XDG configuration
# - https://wiki.archlinux.org/index.php/XDG_Base_Directory
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"

# Non-standard
export XDG_BIN_HOME="${XDG_BIN_HOME:-$HOME/.local/bin}"
export XDG_LIB_HOME="${XDG_LIB_HOME:-$HOME/.local/lib}"
export XDG_OPT_HOME="${XDG_OPT_HOME:-$HOME/.local/opt}"

# Dotfiles dir
export DOTFILES_DIR="${DOTFILES_DIR:-${HOME}/.dotfiles}"

# Editor
export EDITOR=vi
export VISUAL="${EDITOR}"

# Pager
export LESSHISTFILE="${XDG_CACHE_HOME}/less/history"
export LESSKEY="${XDG_CONFIG_HOME}/less/keys"
export LESS="-F -g -i -M -R -S -w -X -z-4"
export LESSCHARSET="utf-8"
export PAGER="less"

# Load core utilities used by other scripts
# shellcheck source=../../../lib/init.sh disable=SC1091
. "${DOTFILES_DIR}/lib/init.sh"

# Append bin directories to path
prepend_path "${DOTFILES_DIR}/bin"
prepend_path "${XDG_BIN_HOME}"

HOMEBREW_BIN_PATH="/opt/homebrew/bin"
if [[ -d "$HOMEBREW_BIN_PATH" ]]; then
  prepend_path "${HOMEBREW_BIN_PATH}"
fi

# Load extra environment files into environment
if [ -d "${XDG_CONFIG_HOME}/environment.d" ]; then
  source_files_in "${XDG_CONFIG_HOME}"/environment.d/*
fi

# Load secrets
if [ -d "${XDG_CONFIG_HOME}/secrets.d" ]; then
  set -o allexport

  for secrets_file in "${XDG_CONFIG_HOME}"/secrets.d/*.env; do
    . $secrets_file
  done

  set +o allexport
fi

# Go to the dotfiles directory
if [[ -n "${DOTFILES_DIR}" ]]; then
  alias dotdir='cd ${DOTFILES_DIR}'
fi
