[settings]
experimental = true

[settings.ruby]
ruby_install = true

[tools]
# language runtimes
deno = ['2', '1.46.1']
neovim = '0.10.2'
node = '18.4.0'
python = '3.10.4'
ruby = ['3.3', '3.2', '3.1']

# shell tools
delta = '0.18.2'
fd = 'latest'
fzf = 'latest'
jless = '0.9.0'
jnv = '0.4.0'
jq = '1.7.1'
just = '1.29.1'
stylua = 'latest'
yq = '4.44.3'

'cargo:taplo-cli' = 'latest'
