[settings]
experimental = true

[settings.ruby]
ruby_install = true

[tools]
# language runtimes
deno = '1.46.1'
neovim = '0.10.0'
node = '18.4.0'
python = '3.10.4'
ruby = ['3.3', '3.2', '3.1']

# shell tools
jless = '0.9.0'
jnv = '0.4.0'
jq = '1.7.1'
just = '1.29.1'
yq = '4.44.3'
delta = '0.18.2'
fzf = 'latest'

'cargo:taplo-cli' = 'latest'
