[settings]
experimental = true

[settings.ruby]
# ruby_install = true

[tools]
# language runtimes
deno = ['2', '1.46.1']
neovim = '0.11.0'
node = ['22', '18.4.0']
ruby = ['3.3', '3.2', '3.1']
java = ['17.0']

python = ['3.12'] # must be after poetry so the poetry bin is first in PATH

# for poetry projects, automatic activation can be done with a local '.mise.toml'
# poetry = {version='latest', pyproject='pyproject.toml'}

# shell dev tools
delta = '0.18.2'
fd = 'latest'
fzf = 'latest'
jless = '0.9.0'
jnv = '0.4.0'
jq = '1.7.1'
just = '1.29.1'
stylua = 'latest'
yq = '4.44.3'
shfmt = 'latest'
kubectl = 'latest'
colima = 'latest'

pandoc = 'latest'
'cargo:taplo-cli' = 'latest'
jj = "latest"

# Broken in osx, use a different fork with `[plugins]` declaration?
# mdbook = 'latest'
