[settings]
experimental = true

status = {missing_tools = "if_other_versions_installed", show_env = false, show_tools = true}

[tools]
# language runtimes
deno   = '1.46.1'
neovim = '0.10.0'
node   = '18.4.0'
python = '3.10.4'
ruby   = '3.3.5'

# shell tools
jless  = '0.9.0'
jnv    = '0.4.0'
jq     = '1.7.1'
just   = '1.29.1'
yq     = '4.44.3'
